### ISSUE TITLE
Build scripts build DEBUG versions, not RELEASE

### ISSUE THREAD

**Issue by rjmurillo** [microsoft/VirtualClient#202]
**Describe the bug**
The build scripts `build.cmd` and `build-packages.cmd` build with the Debug configuration, not Release. 

1. **Optimization**. The release configuration enables the compiler to perform optimizations that are not done in debug mode. These optimizations include advanced code restructuring and removal of unnecessary instructions, which can lead to faster execution times. For example, in release the JIT can perform inlining, where it replaces a method call with the method's body to save the overhead of the call.
2. **No code contracts**. Release mode often exclude code contracts and assertions that are used for checking conditions during development. These checks can slow down the execution because they add extra instructions at runtime.
3. **Non-Optimized Libraries**. When building in debug, the referenced libraries might also be the non-optimized versions, which can further degrade performance.
4. **Non-optimized data structures**. Data structures and algorithms might not be optimized for space and time efficiency in debug mode, as the focus is on readability and debugability for humans.

**To Reproduce**
Inspect the files `build.cmd` and `build-packages.cmd`. The arguments to `dotnet build` and `dotnet pack` are hard coded to `Debug`. 

**Expected behavior**
If building for debug configurations is necessary, then there should be a command line argument to set the version to be built or both should be built by default. 

**Screenshots**
See build results for #201. Example: [Build](https://github.com/microsoft/VirtualClient/actions/runs/6748657055/job/18347447167?pr=201)

```bash
  VirtualClient.Monitors -> D:\a\VirtualClient\VirtualClient\out\bin\Debug\AnyCPU\VirtualClient.Monitors\net6.0\VirtualClient.Monitors.dll
  VirtualClient.Api -> D:\a\VirtualClient\VirtualClient\out\bin\Debug\AnyCPU\VirtualClient.Api\net6.0\VirtualClient.Api.dll
  VirtualClient.TestFramework -> D:\a\VirtualClient\VirtualClient\out\bin\Debug\AnyCPU\VirtualClient.TestFramework\net6.0\VirtualClient.TestFramework.dll
  VirtualClient.ExampleWorkload -> D:\a\VirtualClient\VirtualClient\out\bin\Debug\AnyCPU\VirtualClient.ExampleWorkload\net6.0\ExampleWorkload.dll
  VirtualClient.Actions -> D:\a\VirtualClient\VirtualClient\out\bin\Debug\AnyCPU\VirtualClient.Actions\net6.0\VirtualClient.Actions.dll
```

**Comment by yangpanMS** [comment]
Thank you @rjmurillo . This suggestion is acknowledged and we will work on it shortly. Will update here once we have a PR

**Comment by yangpanMS** [comment]
PR raised at #210
