### ISSUE TITLE
Package Virtual Client for Ubuntu 24.04

### ISSUE THREAD

**Issue by samw-msft** [microsoft/VirtualClient#415]
I noticed that VC is not in the noble or nightly channels for the Ubuntu package do not have virtualclient available from packages.microsoft.com.

The most recent is 23.04 it seems.

Given that 24.04 is an LTS, can you please package this for this distro?

fwiw, I'm an internal Microsoft employee. You can get in touch via Teams / email too.

**Comment by yangpanMS** [comment]
Acknowledged. Working on that right now. At the time I made the linux release the 2404 wasn't available in PMC repo.

**Comment by yangpanMS** [comment]
Addressed in PR https://github.com/microsoft/VirtualClient/pull/416
